const editorSettings = {
	html: {
		id: 1,
		type: 'web',
		languageName: 'Web',
		name: 'HTML',
		alias: 'html',
		language: 'web',
	},
	css: {
		id: 2,
		type: 'web',
		languageName: 'Web',
		name: 'CSS',
		alias: 'css',
		language: 'web',
	},
	javascript: {
		id: 3,
		type: 'web',
		languageName: 'Web',
		name: 'JS',
		alias: 'js',
		language: 'web',
	},
	c_cpp: {
		id: 4,
		type: 'default',
		languageName: 'C++',
		name: 'C++',
		alias: 'cpp',
		language: 'cpp',
	},
	c: {
		id: 5,
		type: 'default',
		languageName: 'C',
		name: 'C',
		alias: 'c',
		language: 'c',
	},
	csharp: {
		id: 6,
		type: 'default',
		languageName: 'C#',
		name: 'C#',
		alias: 'cs',
		language: 'cs',
	},
	java: {
		id: 7,
		type: 'default',
		languageName: 'Java',
		name: 'JAVA',
		alias: 'java',
		language: 'java',
	},
	kotlin: {
		id: 8,
		type: 'default',
		languageName: 'Kotlin',
		name: 'Kotlin',
		alias: 'kt',
		language: 'kt',
	},
	swift: {
		id: 9,
		type: 'default',
		languageName: 'Swift',
		name: 'Swift',
		alias: 'swift',
		language: 'swift',
	},
	python: {
		id: 10,
		type: 'default',
		languageName: 'Python',
		name: 'Python 3',
		alias: 'py',
		language: 'py',
	},
	ruby: {
		id: 11,
		type: 'default',
		languageName: 'Ruby',
		name: 'Ruby',
		alias: 'rb',
		language: 'rb',
	},
	php: {
		id: 12,
		type: 'combined',
		languageName: 'PHP',
		name: 'PHP',
		alias: 'php',
		language: 'php',
	},
};

export default editorSettings;
